/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "zyodfpwunxkyionhcbsn"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5b2RmcHd1bnhreWlvbmhjYnNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc2OTYyMjcsImV4cCI6MjA4MzI3MjIyN30.b-ShTy8oyDcL0Dq_VhCAOxGRYFEwyjoXBDZ18Sl_hvQ"
